# Generated by Django 4.1.7 on 2023-03-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="board",
            new_name="board_obj",
        ),
    ]
