# Generated by Django 4.1.7 on 2023-03-23 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("order_history", models.TextField()),
                ("price", models.IntegerField(default=0)),
                ("adress", models.TextField(default="포장")),
            ],
        ),
    ]
